# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(996, 715)
        Form.setAutoFillBackground(False)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(480, 540, 441, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_submit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_submit.setObjectName("button_submit")
        self.horizontalLayout.addWidget(self.button_submit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 70, 901, 381))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tab_widget = QtWidgets.QTabWidget(self.horizontalLayoutWidget_2)
        self.tab_widget.setObjectName("tab_widget")
        self.tab_current = QtWidgets.QWidget()
        self.tab_current.setObjectName("tab_current")
        self.table_current = QtWidgets.QTableView(self.tab_current)
        self.table_current.setGeometry(QtCore.QRect(0, 0, 891, 351))
        self.table_current.setObjectName("table_current")
        self.tab_widget.addTab(self.tab_current, "")
        self.tab_borrowed = QtWidgets.QWidget()
        self.tab_borrowed.setObjectName("tab_borrowed")
        self.table_borrowed = QtWidgets.QTableView(self.tab_borrowed)
        self.table_borrowed.setGeometry(QtCore.QRect(0, 0, 891, 351))
        self.table_borrowed.setObjectName("table_borrowed")
        self.table_borrowed.raise_()
        self.tab_widget.addTab(self.tab_borrowed, "")
        self.tab_past = QtWidgets.QWidget()
        self.tab_past.setObjectName("tab_past")
        self.table_past = QtWidgets.QTableView(self.tab_past)
        self.table_past.setGeometry(QtCore.QRect(0, 0, 891, 351))
        self.table_past.setObjectName("table_past")
        self.tab_widget.addTab(self.tab_past, "")
        self.horizontalLayout_2.addWidget(self.tab_widget)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(480, 470, 441, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.text_add = QtWidgets.QTextEdit(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_add.sizePolicy().hasHeightForWidth())
        self.text_add.setSizePolicy(sizePolicy)
        self.text_add.setMaximumSize(QtCore.QSize(16777215, 25))
        self.text_add.setBaseSize(QtCore.QSize(50, 20))
        self.text_add.setObjectName("text_add")
        self.horizontalLayout_3.addWidget(self.text_add)
        self.radio_return = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radio_return.setObjectName("radio_return")
        self.horizontalLayout_3.addWidget(self.radio_return)
        self.button_add = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout_3.addWidget(self.button_add)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 20, 271, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_label_puid = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_label_puid.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_label_puid.setFont(font)
        self.label_label_puid.setObjectName("label_label_puid")
        self.horizontalLayout_4.addWidget(self.label_label_puid)
        self.label_puid = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_puid.setFont(font)
        self.label_puid.setObjectName("label_puid")
        self.horizontalLayout_4.addWidget(self.label_puid)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(30, 460, 441, 181))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_puid_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_puid_6.setFont(font)
        self.label_puid_6.setObjectName("label_puid_6")
        self.verticalLayout_3.addWidget(self.label_puid_6)
        self.label_puid_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_puid_2.setFont(font)
        self.label_puid_2.setObjectName("label_puid_2")
        self.verticalLayout_3.addWidget(self.label_puid_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_puid_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_puid_7.setFont(font)
        self.label_puid_7.setObjectName("label_puid_7")
        self.verticalLayout_2.addWidget(self.label_puid_7)
        self.label_puid_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_puid_3.setFont(font)
        self.label_puid_3.setObjectName("label_puid_3")
        self.verticalLayout_2.addWidget(self.label_puid_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        self.tab_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_cancel.setText(_translate("Form", "Cancel"))
        self.button_submit.setText(_translate("Form", "Submit"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_current), _translate("Form", "Taken Equipment"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_borrowed), _translate("Form", "Borrowed Equipment"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_past), _translate("Form", "History"))
        self.text_add.setPlaceholderText(_translate("Form", "Add an item not on the list"))
        self.radio_return.setText(_translate("Form", "Will Return?"))
        self.button_add.setText(_translate("Form", "Add"))
        self.label_label_puid.setText(_translate("Form", "PUID:"))
        self.label_puid.setText(_translate("Form", "XXXXX-XXXXX"))
        self.label_puid_6.setText(_translate("Form", "Credits This Transaction:"))
        self.label_puid_2.setText(_translate("Form", "Credits Remaining :"))
        self.label_puid_7.setText(_translate("Form", "XXXXX-XXXXX"))
        self.label_puid_3.setText(_translate("Form", "XXXXX-XXXXX"))

