# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1139, 778)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_label_puid = QtWidgets.QLabel(self.centralwidget)
        self.label_label_puid.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_label_puid.setFont(font)
        self.label_label_puid.setObjectName("label_label_puid")
        self.horizontalLayout_4.addWidget(self.label_label_puid)
        self.label_puid = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_puid.setFont(font)
        self.label_puid.setObjectName("label_puid")
        self.horizontalLayout_4.addWidget(self.label_puid)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setObjectName("tab_widget")
        self.tab_current = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_current.sizePolicy().hasHeightForWidth())
        self.tab_current.setSizePolicy(sizePolicy)
        self.tab_current.setObjectName("tab_current")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_current)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.table_current = QtWidgets.QTableView(self.tab_current)
        self.table_current.setObjectName("table_current")
        self.horizontalLayout_6.addWidget(self.table_current)
        self.tab_widget.addTab(self.tab_current, "")
        self.tab_quickadd = QtWidgets.QWidget()
        self.tab_quickadd.setObjectName("tab_quickadd")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_quickadd)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.tab_quickadd)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.table_quick = QtWidgets.QTableView(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_quick.sizePolicy().hasHeightForWidth())
        self.table_quick.setSizePolicy(sizePolicy)
        self.table_quick.setMinimumSize(QtCore.QSize(500, 0))
        self.table_quick.setObjectName("table_quick")
        self.verticalLayout_5.addWidget(self.table_quick)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.text_resistorvalue = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_resistorvalue.sizePolicy().hasHeightForWidth())
        self.text_resistorvalue.setSizePolicy(sizePolicy)
        self.text_resistorvalue.setMaximumSize(QtCore.QSize(150, 25))
        self.text_resistorvalue.setObjectName("text_resistorvalue")
        self.horizontalLayout_10.addWidget(self.text_resistorvalue)
        self.combo_resistor = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_resistor.sizePolicy().hasHeightForWidth())
        self.combo_resistor.setSizePolicy(sizePolicy)
        self.combo_resistor.setMaximumSize(QtCore.QSize(100, 16777215))
        self.combo_resistor.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.combo_resistor.setObjectName("combo_resistor")
        self.combo_resistor.addItem("")
        self.combo_resistor.addItem("")
        self.combo_resistor.setItemText(1, "")
        self.combo_resistor.addItem("")
        self.combo_resistor.addItem("")
        self.combo_resistor.addItem("")
        self.horizontalLayout_10.addWidget(self.combo_resistor)
        self.label_10 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(50, 0))
        self.label_10.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(100, 0))
        self.label_11.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.text_resistorquantity = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_resistorquantity.sizePolicy().hasHeightForWidth())
        self.text_resistorquantity.setSizePolicy(sizePolicy)
        self.text_resistorquantity.setMaximumSize(QtCore.QSize(60, 25))
        self.text_resistorquantity.setObjectName("text_resistorquantity")
        self.horizontalLayout_10.addWidget(self.text_resistorquantity)
        self.button_resistoradd = QtWidgets.QPushButton(self.frame)
        self.button_resistoradd.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_resistoradd.setObjectName("button_resistoradd")
        self.horizontalLayout_10.addWidget(self.button_resistoradd)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(450, 0))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.text_capvalue = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_capvalue.sizePolicy().hasHeightForWidth())
        self.text_capvalue.setSizePolicy(sizePolicy)
        self.text_capvalue.setMaximumSize(QtCore.QSize(150, 25))
        self.text_capvalue.setObjectName("text_capvalue")
        self.horizontalLayout_11.addWidget(self.text_capvalue)
        self.combo_cap = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_cap.sizePolicy().hasHeightForWidth())
        self.combo_cap.setSizePolicy(sizePolicy)
        self.combo_cap.setMaximumSize(QtCore.QSize(100, 16777215))
        self.combo_cap.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.combo_cap.setObjectName("combo_cap")
        self.combo_cap.addItem("")
        self.combo_cap.addItem("")
        self.combo_cap.setItemText(1, "")
        self.combo_cap.addItem("")
        self.combo_cap.addItem("")
        self.combo_cap.addItem("")
        self.horizontalLayout_11.addWidget(self.combo_cap)
        self.label_13 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(50, 0))
        self.label_13.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(100, 0))
        self.label_14.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.text_capquantity = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_capquantity.sizePolicy().hasHeightForWidth())
        self.text_capquantity.setSizePolicy(sizePolicy)
        self.text_capquantity.setMaximumSize(QtCore.QSize(60, 25))
        self.text_capquantity.setObjectName("text_capquantity")
        self.horizontalLayout_11.addWidget(self.text_capquantity)
        self.button_capadd = QtWidgets.QPushButton(self.frame)
        self.button_capadd.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_capadd.setObjectName("button_capadd")
        self.horizontalLayout_11.addWidget(self.button_capadd)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(450, 0))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.text_inductorvalue = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_inductorvalue.sizePolicy().hasHeightForWidth())
        self.text_inductorvalue.setSizePolicy(sizePolicy)
        self.text_inductorvalue.setMaximumSize(QtCore.QSize(150, 25))
        self.text_inductorvalue.setObjectName("text_inductorvalue")
        self.horizontalLayout_12.addWidget(self.text_inductorvalue)
        self.combo_inductor = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_inductor.sizePolicy().hasHeightForWidth())
        self.combo_inductor.setSizePolicy(sizePolicy)
        self.combo_inductor.setMaximumSize(QtCore.QSize(100, 16777215))
        self.combo_inductor.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.combo_inductor.setObjectName("combo_inductor")
        self.combo_inductor.addItem("")
        self.combo_inductor.addItem("")
        self.combo_inductor.setItemText(1, "")
        self.combo_inductor.addItem("")
        self.combo_inductor.addItem("")
        self.combo_inductor.addItem("")
        self.horizontalLayout_12.addWidget(self.combo_inductor)
        self.label_16 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(50, 0))
        self.label_16.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_12.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(100, 0))
        self.label_17.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.text_inductorquantity = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_inductorquantity.sizePolicy().hasHeightForWidth())
        self.text_inductorquantity.setSizePolicy(sizePolicy)
        self.text_inductorquantity.setMaximumSize(QtCore.QSize(60, 25))
        self.text_inductorquantity.setObjectName("text_inductorquantity")
        self.horizontalLayout_12.addWidget(self.text_inductorquantity)
        self.button_inductoradd = QtWidgets.QPushButton(self.frame)
        self.button_inductoradd.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_inductoradd.setObjectName("button_inductoradd")
        self.horizontalLayout_12.addWidget(self.button_inductoradd)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(450, 0))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.text_icname = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_icname.sizePolicy().hasHeightForWidth())
        self.text_icname.setSizePolicy(sizePolicy)
        self.text_icname.setMaximumSize(QtCore.QSize(150, 25))
        self.text_icname.setObjectName("text_icname")
        self.horizontalLayout_9.addWidget(self.text_icname)
        spacerItem = QtWidgets.QSpacerItem(162, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.text_icquantity = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_icquantity.sizePolicy().hasHeightForWidth())
        self.text_icquantity.setSizePolicy(sizePolicy)
        self.text_icquantity.setMaximumSize(QtCore.QSize(60, 25))
        self.text_icquantity.setObjectName("text_icquantity")
        self.horizontalLayout_9.addWidget(self.text_icquantity)
        self.button_icadd = QtWidgets.QPushButton(self.frame)
        self.button_icadd.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_icadd.setObjectName("button_icadd")
        self.horizontalLayout_9.addWidget(self.button_icadd)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.verticalLayout_6.addWidget(self.frame)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab_quickadd, "")
        self.tab_borrowed = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_borrowed.sizePolicy().hasHeightForWidth())
        self.tab_borrowed.setSizePolicy(sizePolicy)
        self.tab_borrowed.setObjectName("tab_borrowed")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_borrowed)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.table_borrowed = QtWidgets.QTableView(self.tab_borrowed)
        self.table_borrowed.setObjectName("table_borrowed")
        self.horizontalLayout_5.addWidget(self.table_borrowed)
        self.tab_widget.addTab(self.tab_borrowed, "")
        self.tab_requested = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_requested.sizePolicy().hasHeightForWidth())
        self.tab_requested.setSizePolicy(sizePolicy)
        self.tab_requested.setObjectName("tab_requested")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_requested)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.table_requested = QtWidgets.QTableView(self.tab_requested)
        self.table_requested.setObjectName("table_requested")
        self.verticalLayout_3.addWidget(self.table_requested)
        self.tab_widget.addTab(self.tab_requested, "")
        self.tab_past = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_past.sizePolicy().hasHeightForWidth())
        self.tab_past.setSizePolicy(sizePolicy)
        self.tab_past.setObjectName("tab_past")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_past)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.table_past = QtWidgets.QTableView(self.tab_past)
        self.table_past.setObjectName("table_past")
        self.horizontalLayout_3.addWidget(self.table_past)
        self.tab_widget.addTab(self.tab_past, "")
        self.horizontalLayout_2.addWidget(self.tab_widget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text_search = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_search.sizePolicy().hasHeightForWidth())
        self.text_search.setSizePolicy(sizePolicy)
        self.text_search.setMaximumSize(QtCore.QSize(350, 20))
        self.text_search.setBaseSize(QtCore.QSize(10, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.text_search.setFont(font)
        self.text_search.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_search.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_search.setObjectName("text_search")
        self.horizontalLayout.addWidget(self.text_search)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.button_cancel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_cancel.sizePolicy().hasHeightForWidth())
        self.button_cancel.setSizePolicy(sizePolicy)
        self.button_cancel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        self.button_submit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_submit.sizePolicy().hasHeightForWidth())
        self.button_submit.setSizePolicy(sizePolicy)
        self.button_submit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_submit.setObjectName("button_submit")
        self.horizontalLayout.addWidget(self.button_submit)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1139, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuGenerate_Reprt = QtWidgets.QMenu(self.menuFile)
        self.menuGenerate_Reprt.setObjectName("menuGenerate_Reprt")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClear_Window = QtWidgets.QAction(MainWindow)
        self.actionClear_Window.setObjectName("actionClear_Window")
        self.actionBorrowed_Equipment = QtWidgets.QAction(MainWindow)
        self.actionBorrowed_Equipment.setObjectName("actionBorrowed_Equipment")
        self.actionComponents_Sold = QtWidgets.QAction(MainWindow)
        self.actionComponents_Sold.setObjectName("actionComponents_Sold")
        self.actionRecent_PUID_s = QtWidgets.QAction(MainWindow)
        self.actionRecent_PUID_s.setObjectName("actionRecent_PUID_s")
        self.menuGenerate_Reprt.addAction(self.actionBorrowed_Equipment)
        self.menuGenerate_Reprt.addAction(self.actionComponents_Sold)
        self.menuGenerate_Reprt.addAction(self.actionRecent_PUID_s)
        self.menuFile.addAction(self.menuGenerate_Reprt.menuAction())
        self.menuFile.addAction(self.actionClear_Window)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_label_puid.setText(_translate("MainWindow", "PUID:"))
        self.label_puid.setText(_translate("MainWindow", "XXXXX-XXXXX"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_current), _translate("MainWindow", "Component List"))
        self.label_9.setText(_translate("MainWindow", "Resistor"))
        self.label.setText(_translate("MainWindow", "Value:"))
        self.combo_resistor.setItemText(0, _translate("MainWindow", "Kilo (k)"))
        self.combo_resistor.setItemText(2, _translate("MainWindow", "Giga (G)"))
        self.combo_resistor.setItemText(3, _translate("MainWindow", "Mega (M)"))
        self.combo_resistor.setItemText(4, _translate("MainWindow", "Milli (m)"))
        self.label_10.setText(_translate("MainWindow", "Ω"))
        self.label_11.setText(_translate("MainWindow", "Quantity:"))
        self.button_resistoradd.setText(_translate("MainWindow", "Add"))
        self.label_12.setText(_translate("MainWindow", "Capacitor"))
        self.label_3.setText(_translate("MainWindow", "Value:"))
        self.combo_cap.setItemText(0, _translate("MainWindow", "micro (µ)"))
        self.combo_cap.setItemText(2, _translate("MainWindow", "milli (m)"))
        self.combo_cap.setItemText(3, _translate("MainWindow", "nano (n)"))
        self.combo_cap.setItemText(4, _translate("MainWindow", "pico (p)"))
        self.label_13.setText(_translate("MainWindow", "F"))
        self.label_14.setText(_translate("MainWindow", "Quantity:"))
        self.button_capadd.setText(_translate("MainWindow", "Add"))
        self.label_15.setText(_translate("MainWindow", "Inductor"))
        self.label_4.setText(_translate("MainWindow", "Value:"))
        self.combo_inductor.setItemText(0, _translate("MainWindow", "milli (m)"))
        self.combo_inductor.setItemText(2, _translate("MainWindow", "micro (µ)"))
        self.combo_inductor.setItemText(3, _translate("MainWindow", "nano (n)"))
        self.combo_inductor.setItemText(4, _translate("MainWindow", "pico (p)"))
        self.label_16.setText(_translate("MainWindow", "H"))
        self.label_17.setText(_translate("MainWindow", "Quantity:"))
        self.button_inductoradd.setText(_translate("MainWindow", "Add"))
        self.label_6.setText(_translate("MainWindow", "IC"))
        self.label_7.setText(_translate("MainWindow", "Part No:"))
        self.label_8.setText(_translate("MainWindow", "Quantity:"))
        self.button_icadd.setText(_translate("MainWindow", "Add"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_quickadd), _translate("MainWindow", "Quick Add"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_borrowed), _translate("MainWindow", "Borrowed Equipment"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_requested), _translate("MainWindow", "Requested Equipment"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_past), _translate("MainWindow", "History"))
        self.text_search.setPlaceholderText(_translate("MainWindow", "Search"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
        self.button_submit.setText(_translate("MainWindow", "Save"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuGenerate_Reprt.setTitle(_translate("MainWindow", "Generate Reprt"))
        self.actionClear_Window.setText(_translate("MainWindow", "Clear Window"))
        self.actionBorrowed_Equipment.setText(_translate("MainWindow", "Borrowed Equipment"))
        self.actionComponents_Sold.setText(_translate("MainWindow", "Components Sold"))
        self.actionRecent_PUID_s.setText(_translate("MainWindow", "Recent PUID\'s"))

